### ISSUE TITLE
Add some time policy

### ISSUE THREAD

**Issue by vmario89** [ParoaPe/USBGuardGUI#16]
hi,
this tool works well. however, contents of trusted USB devices may change from good to bad (like a plain usb data stick). What do you think about additional modes/options like
- allowing the device only for a certain amount of time (some minutes, hours, days, ..)
- allow only for the time it was attached; re-attaching later needs to re-allow in GUI

**Comment by Bigyls** [comment]
I'm not sure that these proposals are what I want for this simple tool. The aim of this little project is to graphically warn the user that a USB flash drive has been plugged into the PC and that it has just been detected by USBGuard, and thus set the user's policy. 
But I want to thank you for these brilliant ideas.
